name: Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
      runs-on: ubuntu-latest

      steps:
      - name: Check out github repository
        uses: actions/checkout@v2

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true 
